const brazilianStates = [
    { name: 'Acre', capital: 'Rio Branco', region: 'norte', src: './assets/AC-flag.png' },
    { name: 'Alagoas', capital: 'Maceió', region: 'nordeste', src: './assets/AL-flag.png' },
    { name: 'Amazonas', capital: 'Manaus', region: 'norte', src: './assets/AM-flag.png' },
    { name: 'Amapá', capital: 'Macapá', region: 'norte', src: './assets/AP-flag.png' },
    { name: 'Bahia', capital: 'Salvador', region: 'nordeste', src: './assets/BA-flag.png' },
    { name: 'Ceará', capital: 'Fortaleza', region: 'nordeste', src: './assets/CE-flag.png' },
    { name: 'Distrito Federal', capital: 'Não tem', region: 'centro-oeste', src: './assets/DF-flag.png'},
    { name: 'Espírito Santo', capital: 'Espírito Santo', region: 'sudeste', src: './assets/ES-flag.png' },
    { name: 'Goiás', capital: 'Goiânia', region: 'centro-oeste', src: './assets/GO-flag.png' },
    { name: 'Maranhão', capital: 'São Luís', region: 'nordeste', src: './assets/MA-flag.png' },
    { name: 'Minas Gerais', capital: 'Belo Horizonte', region: 'sudeste', src: './assets/MG-flag.png' },
    { name: 'Mato Grosso do Sul', capital: 'Campo Grande', region: 'centro-oeste', src: './assets/MS-flag.png' },
    { name: 'Mato Grosso', capital: 'Cuiabá', region: 'centro-oeste', src: './assets/MT-flag.png' },
    { name: 'Pará', capital: 'Belém', region: 'norte', src: './assets/PA-flag.png' },
    { name: 'Paraíba', capital: 'João Pessoa', region: 'nordeste', src: './assets/PB-flag.png' },
    { name: 'Pernambuco', capital: 'Recife', region: 'nordeste', src: './assets/PE-flag.png' },
    { name: 'Piauí', capital: 'Terezina', region: 'nordeste', src: './assets/PI-flag.png' },
    { name: 'Paraná', capital: 'Curitiba', region: 'sul', src: './assets/PR-flag.png' },
    { name: 'Rio de Janeiro', capital: 'Rio de Janeiro', region: 'sudeste', src: './assets/RJ-flag.png' },
    { name: 'Rio Grande do Norte', capital: 'Natal', region: 'nordeste', src: './assets/RN-flag.png' },
    { name: 'Rondônia', capital: 'Porto Velho', region: 'norte', src: './assets/RO-flag.png' },
    { name: 'Roraima', capital: 'Boa Vista', region: 'norte', src: './assets/RR-flag.png' },
    { name: 'Rio Grande do Sul', capital: 'Porto Alegre', region: 'sul', src: './assets/RS-flag.png' },
    { name: 'Santa Catarina', capital: 'Florianópolis', region: 'sul', src: './assets/SC-flag.png' },
    { name: 'Sergipe', capital: 'Aracaju', region: 'nordeste', src: './assets/SE-flag.png' },
    { name: 'São Paulo', capital: 'São Paulo', region: 'sudeste', src: './assets/SP-flag.png' },
    { name: 'Tocantins', capital: 'Palmas', region: 'norte', src: './assets/TO-flag.png' },
]